### ISSUE TITLE
Print PDF

### ISSUE THREAD

**Issue by Cris-lml007** [abhigkar/YHK-Cat-Thermal-Printer#3]
I find this project interesting, after hours of looking for a driver or way to use my mini printer, I managed to make it work with this project, I still analyze your code and I hope to understand it, but my question is if it is possible to implement PDF printing?

**Comment by janamach** [comment]
@Cris-lml007 A very quick hack is to replace line 133 in the original script with a block of code that will read your pdf file. To do that, replace
```
img = PIL.Image.open("Turtle.jpg")
```
with
```
# Load pdf2image library
from pdf2image import convert_from_path

#Read PDF file called test.pdf:
images = convert_from_path('test.pdf')

# Get first page of the PDF into a variable called img (0 for page 1, 1 for page 2, etc)
img = images[0]
```
The end of the code stays the same:
```
printImage(s,img)
s.close()
```
You might have to install pdf2image with `pip install pdf2image` first.

@abhigkar Thank you for providing such a comprehensive guide for getting this thing to work! I am impressed how functional this cheap little printer is.

**Comment by abhigkar** [comment]
@Cris-lml007 , I am really sorry, I am bit lazy to check my GitHub comments frequently. 

But just to answer your question, this mini printer has some serious limitations on its printing size, so if you like to print a PDF that contains lots of text, this is not the one you should use. 

But the PDF contains just a single image , umm @janamach suggestion might work. However I have not tested that yet.

Eventually, the printer firmware expects the input image in binary format , pdf2image image library will extract and convert pages to images and then the images can be send to the printer.

@janamach thank you so much for your kind word, I am really glad that my work is really helping other. I will be more than happy if you can create PR for this modification.

**Comment by Cris-lml007** [comment]
after studying the printer, its behavior and the limitations of its memory, I managed to rewrite all the code and implement PDF printing, in addition to a GUI and a stable connection, this so that documents can be sent without connecting several times with the printer, [here](https://github.com/Cris-lml007/YHK-miniPrinter) is the project.  I would appreciate if you could collaborate with the implementation of the use of CUPS.
